package main

import (
	"context"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/janlauber/one-click/pkg/controller"
	"github.com/janlauber/one-click/pkg/env"
	"github.com/janlauber/one-click/pkg/k8s"
	platformapi "github.com/janlauber/one-click/pkg/platform/api"
	"github.com/janlauber/one-click/pkg/reconciler"
	"github.com/janlauber/one-click/pkg/runtime_deploy"
	"github.com/janlauber/one-click/pkg/secrets"
	"github.com/janlauber/one-click/pkg/watcher"
	"github.com/labstack/echo/v5"
	"github.com/pocketbase/pocketbase"
	"github.com/pocketbase/pocketbase/apis"
	"github.com/pocketbase/pocketbase/core"
	"github.com/pocketbase/pocketbase/plugins/jsvm"
	"github.com/pocketbase/pocketbase/plugins/migratecmd"
	"github.com/pocketbase/pocketbase/tools/cron"
)

func defaultPublicDir() string {
	if strings.HasPrefix(os.Args[0], os.TempDir()) {
		// most likely ran with go run
		return "./pb_public"
	}

	return filepath.Join(os.Args[0], "../pb_public")
}

func init() {
	env.Init()
	k8s.Init()
}

func main() {
	app := pocketbase.New()

	var publicDirFlag string

	// add "--publicDir" option flag
	app.RootCmd.PersistentFlags().StringVar(
		&publicDirFlag,
		"publicDir",
		defaultPublicDir(),
		"the directory to serve static files",
	)
	migrationsDir := "" // default to "pb_migrations" (for js) and "migrations" (for go)

	// load js files to allow loading external JavaScript migrations
	jsvm.MustRegister(app, jsvm.Config{
		// Dir: migrationsDir,
		MigrationsDir: migrationsDir,
	})

	// register the `migrate` command
	migratecmd.MustRegister(app, app.RootCmd, migratecmd.Config{
		TemplateLang: migratecmd.TemplateLangJS, // or migratecmd.TemplateLangGo (default)
		Dir:          migrationsDir,
		Automigrate:  true,
	})

	app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
		// serves static files from the provided public dir (if exists)
		e.Router.GET("/*", apis.StaticDirectoryHandler(os.DirFS(publicDirFlag), true))

		return nil
	})

	app.OnRecordBeforeCreateRequest().Add(func(e *core.RecordCreateEvent) error {
		switch e.Collection.Name {
		case "rollouts":
			return controller.HandleRolloutCreate(e, app)
		}
		return nil
	})

	app.OnRecordBeforeUpdateRequest().Add(func(e *core.RecordUpdateEvent) error {
		switch e.Collection.Name {
		case "rollouts":
			return controller.HandleRolloutUpdate(e, app)
		}
		return nil
	})

	app.OnRecordBeforeDeleteRequest().Add(func(e *core.RecordDeleteEvent) error {
		switch e.Collection.Name {
		case "rollouts":
			return controller.HandleRolloutDelete(e, app)
		case "deployments":
			return controller.HandleDeploymentDelete(e, app)
		case "projects":
			return controller.HandleProjectDelete(e, app)
		}
		return nil
	})

	app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
		// get status of a specific deployment
		e.Router.GET("/pb/:projectId/:deploymentId/status", func(c echo.Context) error {
			projectId := c.PathParam("projectId")
			deploymentId := c.PathParam("deploymentId")

			return controller.HandleDeploymentStatus(c, app, projectId, deploymentId)
		}, apis.RequireRecordAuth("users"))

		e.Router.GET("/pb/:projectId/:deploymentId/metrics", func(c echo.Context) error {
			projectId := c.PathParam("projectId")
			deploymentId := c.PathParam("deploymentId")

			return controller.HandleDeploymentMetrics(c, app, projectId, deploymentId)
		}, apis.RequireRecordAuth("users"))

		e.Router.GET("/pb/:projectId/:deploymentId/events", func(c echo.Context) error {
			projectId := c.PathParam("projectId")
			deploymentId := c.PathParam("deploymentId")

			return controller.HandleDeploymentEvents(c, app, projectId, deploymentId)
		}, apis.RequireRecordAuth("users"))

		e.Router.GET("/pb/:projectId/:podName/logs", func(c echo.Context) error {
			projectId := c.PathParam("projectId")
			podName := c.PathParam("podName")

			return k8s.GetRolloutLogs(c.Response().Writer, projectId, podName)
		}, apis.RequireRecordAuth("users"))

		e.Router.GET("/pb/blueprints/:blueprintId", func(c echo.Context) error {
			blueprintId := c.PathParam("blueprintId")

			return controller.HandleBlueprint(c, app, blueprintId)
		}, apis.RequireRecordAuth("users"))

		e.Router.POST("/pb/blueprints/shared/:blueprintId", func(c echo.Context) error {
			blueprintId := c.PathParam("blueprintId")

			return controller.HandleBlueprintAdd(c, app, blueprintId)
		}, apis.RequireRecordAuth("users"))

		e.Router.POST("/pb/auto-update/:autoUpdateId", func(c echo.Context) error {
			// TODO: change the auth to be a token generated by the user
			autoUpdateId := c.PathParam("autoUpdateId")

			return controller.HandleAutoUpdate(c, app, autoUpdateId)
		})

		e.Router.GET("/pb/cluster-info", func(c echo.Context) error {
			return controller.HandleClusterInfo(c, app)
			// }, apis.RequireRecordAuth("users"))
		})

		// delete a pod of a rollout by pod name
		e.Router.DELETE("/pb/:projectId/pod/:podName", func(c echo.Context) error {
			projectId := c.PathParam("projectId")
			podName := c.PathParam("podName")

			return controller.HandlePodDelete(c, app, projectId, podName)
		}, apis.RequireRecordAuth("users"))

		// delete a job
		e.Router.DELETE("/pb/:projectId/job/:jobId", func(c echo.Context) error {
			projectId := c.PathParam("projectId")
			jobId := c.PathParam("jobId")

			return controller.HandleJobDelete(c, app, projectId, jobId)
		}, apis.RequireRecordAuth("users"))

		// websocket for deployments status
		e.Router.GET("/ws/k8s/deployments", watcher.WsK8sDeploymentsHandler)

		// websocket for pod logs
		e.Router.GET("/ws/k8s/logs", watcher.WsK8sRolloutLogsHandler)

		// websocket for rollout events
		e.Router.GET("/ws/k8s/events", watcher.WsK8sRolloutEventsHandler)

		// Cloud Account APIs
		e.Router.POST("/api/v1/cloud-accounts", func(c echo.Context) error {
			return controller.HandleCloudAccountCreate(c, app)
		}, apis.RequireRecordAuth("users"))

		e.Router.GET("/api/v1/cloud-accounts", func(c echo.Context) error {
			return controller.HandleCloudAccountList(c, app)
		}, apis.RequireRecordAuth("users"))

		e.Router.POST("/api/v1/cloud-accounts/:id/validate", func(c echo.Context) error {
			accountId := c.PathParam("id")
			return controller.HandleCloudAccountValidate(c, app, accountId)
		}, apis.RequireRecordAuth("users"))

		e.Router.GET("/api/v1/cloud-accounts/:id/regions", func(c echo.Context) error {
			accountId := c.PathParam("id")
			return controller.HandleCloudAccountRegions(c, app, accountId)
		}, apis.RequireRecordAuth("users"))

		// Cost estimation
		e.Router.POST("/api/v1/cost/estimate", func(c echo.Context) error {
			return controller.HandleCostEstimate(c, app)
		}, apis.RequireRecordAuth("users"))

		// Cloud deployments — backed by REAL pkg/providers code (AWS SDK v2,
		// Google Cloud Run SDK).  Whether a Deploy call actually provisions
		// depends on the credentials in the referenced cloud_accounts row;
		// without valid credentials the provider returns its actual error.
		e.Router.POST("/api/v1/cloud-deployments", func(c echo.Context) error {
			return controller.HandleCloudDeploymentCreate(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/cloud-deployments", func(c echo.Context) error {
			return controller.HandleCloudDeploymentList(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/cloud-deployments/:id", func(c echo.Context) error {
			return controller.HandleCloudDeploymentGet(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.DELETE("/api/v1/cloud-deployments/:id", func(c echo.Context) error {
			return controller.HandleCloudDeploymentDestroy(c, app)
		}, apis.RequireRecordAuth("users"))

		// Phase 3.9.1 — Reconciler observability endpoints.
		//
		// /metrics — JSON snapshot of in-memory counters (atomic; restart resets)
		// /metrics/prom — Prometheus text exposition; cardinality-bounded
		// /incident/:targetID — Phase 3.9.6 forensic reconstruction
		//
		// Auth: gated by the same PocketBase user auth as other routes.
		// /metrics/prom is also gated to prevent unauthenticated discovery;
		// operators wanting scraping should configure their scraper with
		// the appropriate auth credentials.
		e.Router.GET("/api/v1/reconciler/metrics", controller.HandleReconcilerMetrics,
			apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/reconciler/metrics/prom", controller.HandleReconcilerMetricsProm,
			apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/reconciler/incident/:targetID", controller.HandleReconcilerIncident,
			apis.RequireRecordAuth("users"))

		// Phase 3.9.4 — persistent incident operator surface.
		e.Router.GET("/api/v1/reconciler/incidents", controller.HandleReconcilerIncidentList,
			apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/reconciler/incidents/:id", controller.HandleReconcilerIncidentGet,
			apis.RequireRecordAuth("users"))
		e.Router.POST("/api/v1/reconciler/incidents/:id/transition", controller.HandleReconcilerIncidentTransition,
			apis.RequireRecordAuth("users"))

		// Phase 3.9.5 — runtime determinism + forensic export.
		e.Router.GET("/api/v1/reconciler/forensic-snapshot/:targetID",
			controller.HandleReconcilerForensicSnapshot,
			apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/reconciler/invariant-audit",
			controller.HandleReconcilerInvariantAudit,
			apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/reconciler/metric-truthfulness",
			controller.HandleReconcilerMetricTruthfulness,
			apis.RequireRecordAuth("users"))

		// Phase 3.9.6 — runtime explainability surfaces.
		e.Router.GET("/api/v1/reconciler/decisions",
			controller.HandleReconcilerDecisions,
			apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/reconciler/narrative/:targetID",
			controller.HandleReconcilerNarrative,
			apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/reconciler/contradictions",
			controller.HandleReconcilerContradictions,
			apis.RequireRecordAuth("users"))

		// Phase 3.10 — operator truth surface.
		e.Router.GET("/api/v1/reconciler/observations", func(c echo.Context) error {
			return controller.HandleProviderObservationList(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/reconciler/drifts", func(c echo.Context) error {
			return controller.HandleProviderDriftList(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/reconciler/truth-status", func(c echo.Context) error {
			return controller.HandleRuntimeTruthStatus(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.POST("/api/v1/reconciler/verify-export-hash",
			controller.HandleVerifyExportHash,
			apis.RequireRecordAuth("users"))

		// Phase 4.8 — Operational Platform Surfaces (read-only query layer).
		// When AUTOSTACK_DEMO_MODE=true, the surface is backed by a seeded
		// in-memory store with three example executions so the UI renders
		// meaningful data. Otherwise the Noop store is used; production wires
		// the real PocketBase-backed store once snapshot persistence is up.
		platformGroup := e.Router.Group("/api/v1/platform",
			apis.RequireRecordAuth("users"))
		var pstore platformapi.PlatformStore
		if os.Getenv("AUTOSTACK_DEMO_MODE") == "true" || os.Getenv("AUTOSTACK_DEMO_MODE") == "1" {
			pstore = platformapi.NewSeededPlatformStore()
			log.Printf("[platform-api] using SeededPlatformStore (AUTOSTACK_DEMO_MODE=true)")
		} else {
			pstore = platformapi.NoopPlatformStore{}
		}
		platformapi.RegisterRoutes(platformGroup, pstore)

		// ── Real local-Docker runtime deployment engine ──────────────────
		// Lifecycle: planned → validating → provisioning → deploying →
		// verifying → stabilized → certified.  Real docker commands;
		// real state transitions persisted to runtime_deployments +
		// runtime_deployment_events. See pkg/runtime_deploy.
		e.Router.GET("/api/v1/runtime/health", func(c echo.Context) error {
			return controller.HandleRuntimeHealth(c, app)
		}) // intentionally unauthenticated — health probe must always answer
		e.Router.POST("/api/v1/runtime/deployments", func(c echo.Context) error {
			return controller.HandleRuntimeDeploymentCreate(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/runtime/deployments", func(c echo.Context) error {
			return controller.HandleRuntimeDeploymentList(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/runtime/deployments/:id", func(c echo.Context) error {
			return controller.HandleRuntimeDeploymentGet(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/runtime/deployments/:id/events", func(c echo.Context) error {
			return controller.HandleRuntimeDeploymentEvents(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/runtime/deployments/:id/logs", func(c echo.Context) error {
			return controller.HandleRuntimeDeploymentLogs(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.POST("/api/v1/runtime/deployments/:id/rollback", func(c echo.Context) error {
			return controller.HandleRuntimeDeploymentRollback(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/runtime/deployments/:id/observations", func(c echo.Context) error {
			return controller.HandleRuntimeDeploymentObservations(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.GET("/api/v1/runtime/deployments/:id/replay", func(c echo.Context) error {
			return controller.HandleRuntimeDeploymentReplay(c, app)
		}, apis.RequireRecordAuth("users"))
		e.Router.DELETE("/api/v1/runtime/deployments/:id", func(c echo.Context) error {
			return controller.HandleRuntimeDeploymentDestroy(c, app)
		}, apis.RequireRecordAuth("users"))

		return nil
	})

	app.OnAfterBootstrap().Add(func(e *core.BootstrapEvent) error {
		scheduler := cron.New()

		// Run image update every minute
		scheduler.MustAdd("autoUpdate", env.Config.CronTick, func() {
			err := controller.AutoUpdateController(app)
			if err != nil {
				log.Printf("Error updating image: %v\n", err)
			}
		})

		scheduler.Start()

		// Encryption-key health check. If AUTOSTACK_ENCRYPTION_KEY is missing
		// or malformed, we do NOT silently fall through to plaintext — that
		// would re-introduce the very security gap pkg/secrets exists to
		// close. Log loudly. Cloud-account writes will fail downstream.
		if err := secrets.EnsureConfigured(); err != nil {
			log.Printf("[ENCRYPTION_NOT_CONFIGURED] %v — cloud_accounts writes/reads will fail until AUTOSTACK_ENCRYPTION_KEY is set", err)
		} else {
			log.Printf("[ENCRYPTION_READY] key_fp=%s", secrets.KeyFingerprint())
		}

		// Start cloud reconciler. The crash-recovery sweep is invoked
		// synchronously inside Start() under the reconciler's start mutex
		// — see Reconciler.Start for the ordering invariant.
		cloudReconciler := reconciler.New(app, reconciler.DefaultConfig())
		cloudReconciler.Start()
		// Phase 3.9.1: publish the reconciler reference so HTTP handlers
		// registered in OnBeforeServe can read metrics + reconstruct
		// incidents. Singleton-by-design; one reconciler per process.
		reconciler.SetActive(cloudReconciler)

		// Phase 2.5: start the retention/cleanup goroutine. Best-effort
		// retention of `operations` and `deployment_history`; honors
		// AUTOSTACK_CLEANUP_ENABLED=false to skip entirely (compliance
		// hold use-case).
		reconciler.StartCleanupOnBoot(app)

		// Real local-Docker runtime engine. Probes docker availability;
		// on failure, the engine still runs but rejects deployments with
		// a clear error message (no silent fallback). Disable entirely
		// with AUTOSTACK_RUNTIME_ENGINE=off.
		if os.Getenv("AUTOSTACK_RUNTIME_ENGINE") != "off" {
			rtStore := runtime_deploy.NewStore(app)
			rtDriver := runtime_deploy.NewDockerDriver()
			rtEngine := runtime_deploy.NewEngine(rtStore, rtDriver)
			rtEngine.Start(context.Background())
			controller.SetActiveRuntime(rtEngine, rtStore, rtDriver)
			log.Printf("[runtime-engine] started worker_id=%s", runtime_deploy.WorkerID())

			// Continuous reconciliation loop. Runs on its own ticker so the
			// lifecycle engine and the drift detector don't share a goroutine.
			// Disable with AUTOSTACK_RECONCILER=off.
			if os.Getenv("AUTOSTACK_RECONCILER") != "off" {
				rtReconciler := runtime_deploy.NewReconciler(rtStore, rtDriver)
				rtReconciler.Start(context.Background())
			}
		}

		return nil
	})

	if err := app.Start(); err != nil {
		log.Fatal(err)
	}
}
