package planner

// Phase 4.0 — PlanNode and PlanGraph node types.
//
// A PlanNode represents one unit of infrastructure that the planner
// has a decision about. Nodes are generated from DesiredState.Services
// and DesiredState.Dependencies. The graph edges come from DependsOn
// and RequiredBy declarations.

// NodeType classifies what kind of infrastructure unit a node represents.
type NodeType string

const (
	NodeTypeService    NodeType = "service"
	NodeTypeNetwork    NodeType = "network"
	NodeTypeSecret     NodeType = "secret"
	NodeTypeDatabase   NodeType = "database"
	NodeTypeQueue      NodeType = "queue"
	NodeTypeCache      NodeType = "cache"
	NodeTypeIngress    NodeType = "ingress"
	NodeTypeStorage    NodeType = "storage"
	NodeTypePolicy     NodeType = "policy"
	NodeTypeDeployment NodeType = "deployment"
)

// AllNodeTypes is the canonical registry. Adding a NodeType here is the
// only way to introduce a new node category.
var AllNodeTypes = []NodeType{
	NodeTypeService,
	NodeTypeNetwork,
	NodeTypeSecret,
	NodeTypeDatabase,
	NodeTypeQueue,
	NodeTypeCache,
	NodeTypeIngress,
	NodeTypeStorage,
	NodeTypePolicy,
	NodeTypeDeployment,
}

// ActionType is what the planner intends to do with a node.
type ActionType string

const (
	ActionCreate   ActionType = "create"
	ActionUpdate   ActionType = "update"
	ActionDelete   ActionType = "delete"
	ActionRollback ActionType = "rollback"
	ActionNoOp     ActionType = "no-op"
	ActionSimulate ActionType = "simulate" // never executes; simulation output only
)

// RiskLevel classifies the operational impact of a planned action.
type RiskLevel string

const (
	RiskLevelLow      RiskLevel = "low"
	RiskLevelMedium   RiskLevel = "medium"
	RiskLevelHigh     RiskLevel = "high"
	RiskLevelCritical RiskLevel = "critical"
)

// ConfidenceLevel classifies the planner's confidence in a decision.
type ConfidenceLevel string

const (
	ConfidenceLevelHigh   ConfidenceLevel = "high"
	ConfidenceLevelMedium ConfidenceLevel = "medium"
	ConfidenceLevelLow    ConfidenceLevel = "low"
)

// PlanNode is a single vertex in the PlanGraph. It is generated by
// BuildPlanGraph from a DesiredState. Nodes are immutable once the
// graph is built.
type PlanNode struct {
	// ID matches the ServiceSpec.ID or DependencySpec.ID that generated it.
	ID string `json:"id"`

	// Type classifies the infrastructure kind.
	Type NodeType `json:"type"`

	// Provider is the cloud provider string ("aws-ecs", "cloud-run", etc.).
	Provider string `json:"provider"`

	// Dependencies is the sorted list of node IDs this node depends on.
	// An edge from A→B means A must be applied AFTER B.
	Dependencies []string `json:"dependencies"`

	// ReverseDependencies is the sorted list of node IDs that depend on this one.
	// Computed during graph construction, not declared.
	ReverseDependencies []string `json:"reverse_dependencies"`

	// DesiredAction is what the planner intends to do with this node.
	DesiredAction ActionType `json:"desired_action"`

	// RiskLevel is the classified risk of DesiredAction.
	RiskLevel RiskLevel `json:"risk_level"`

	// EvidenceRefs are pointers to reconciler-layer records that justify
	// this node's existence or risk classification.
	EvidenceRefs []EvidenceRef `json:"evidence_refs"`

	// PolicyRefs are IDs of PolicySpecs that authorize this action.
	PolicyRefs []string `json:"policy_refs"`

	// RollbackRefs are node IDs that must be rolled back before this node
	// if the plan is aborted mid-execution.
	RollbackRefs []string `json:"rollback_refs"`

	// Constraints are ConstraintSpec IDs that apply to this node.
	Constraints []string `json:"constraints"`

	// WhyNeeded explains in human-readable text why this node requires action.
	WhyNeeded string `json:"why_needed"`

	// WhyRisk explains why the risk level was assigned.
	WhyRisk string `json:"why_risk"`

	// IsOrphan is true when a node has no declared dependencies AND no
	// other node depends on it. Orphan nodes are included in the graph
	// but flagged for operator review.
	IsOrphan bool `json:"is_orphan"`

	// CanRollback is false for irreversible actions (destructive deletes
	// where the provider does not support restore).
	CanRollback bool `json:"can_rollback"`
}
