#!/usr/bin/env bash
# AutoStack Installer — Single-node Docker deployment
# Target: new developer operational in under 15 minutes.
#
# Usage:
#   curl -fsSL <install-url> | bash
#   or: bash scripts/install/install.sh
#
# Requirements:
#   - Docker >= 20.10
#   - Docker Compose v2
#   - 2 GB RAM, 10 GB disk
#
# This installer does NOT require cloud credentials.
# Cloud provider support is configured after first login.
set -euo pipefail

AUTOSTACK_VERSION="${AUTOSTACK_VERSION:-v7.0.0}"
INSTALL_DIR="${AUTOSTACK_DIR:-$HOME/.autostack}"
DATA_DIR="${AUTOSTACK_DATA_DIR:-$HOME/.autostack/data}"
LOG_FILE="/tmp/autostack-install.log"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()    { echo -e "${GREEN}[autostack]${NC} $*"; }
warn()   { echo -e "${YELLOW}[warn]${NC} $*"; }
error()  { echo -e "${RED}[error]${NC} $*" >&2; }
die()    { error "$*"; exit 1; }

# ── Pre-flight checks ────────────────────────────────────────────────────────

check_docker() {
    command -v docker &>/dev/null || die "Docker not found. Install Docker >= 20.10 first: https://docs.docker.com/get-docker/"
    docker info &>/dev/null || die "Docker daemon not running. Start Docker and retry."
    log "Docker: $(docker --version)"
}

check_compose() {
    docker compose version &>/dev/null || die "Docker Compose v2 not found. Install via: https://docs.docker.com/compose/install/"
    log "Docker Compose: $(docker compose version)"
}

check_memory() {
    local mem_mb
    if command -v free &>/dev/null; then
        mem_mb=$(free -m | awk '/^Mem:/ {print $2}')
        if [[ "$mem_mb" -lt 1800 ]]; then
            warn "Available memory: ${mem_mb}MB. AutoStack recommends >= 2GB."
        else
            log "Memory: ${mem_mb}MB OK"
        fi
    fi
}

# ── Installation ─────────────────────────────────────────────────────────────

setup_directories() {
    log "Setting up directories: $INSTALL_DIR"
    mkdir -p "$DATA_DIR/pocketbase"
    mkdir -p "$DATA_DIR/prometheus"
    mkdir -p "$DATA_DIR/grafana"
}

generate_secrets() {
    log "Generating encryption key..."
    if [[ -f "$INSTALL_DIR/.env" ]]; then
        warn "Existing .env found at $INSTALL_DIR/.env — skipping key generation."
        return
    fi
    local key
    key=$(openssl rand -hex 32 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(32))")
    cat > "$INSTALL_DIR/.env" <<EOF
# AutoStack environment configuration
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file to version control.

AUTOSTACK_ENCRYPTION_KEY=$key
AUTOSTACK_VERSION=$AUTOSTACK_VERSION
AUTOSTACK_DATA_DIR=$DATA_DIR
EOF
    chmod 600 "$INSTALL_DIR/.env"
    log "Encryption key written to $INSTALL_DIR/.env"
}

write_compose() {
    cat > "$INSTALL_DIR/docker-compose.yaml" <<'COMPOSE'
services:
  pocketbase:
    image: ghcr.io/janlauber/autostack:${AUTOSTACK_VERSION:-v7.0.0}
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ${AUTOSTACK_DATA_DIR:-./data}/pocketbase:/pb/pb_data
    environment:
      - AUTOSTACK_ENCRYPTION_KEY=${AUTOSTACK_ENCRYPTION_KEY}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8090/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  prometheus:
    image: prom/prometheus:v2.45.0
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ${AUTOSTACK_DATA_DIR:-./data}/prometheus:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:10.2.0
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ${AUTOSTACK_DATA_DIR:-./data}/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-autostack}
COMPOSE

    cat > "$INSTALL_DIR/prometheus.yml" <<'PROM'
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'autostack'
    static_configs:
      - targets: ['pocketbase:8090']
    metrics_path: '/api/v1/reconciler/metrics/prom'
PROM
    log "docker-compose.yaml written to $INSTALL_DIR/"
}

start_services() {
    log "Starting AutoStack..."
    cd "$INSTALL_DIR"
    docker compose --env-file .env up -d
    log "Waiting for PocketBase to be healthy..."
    local attempts=0
    until docker compose exec pocketbase wget -qO- http://localhost:8090/api/health &>/dev/null; do
        attempts=$((attempts + 1))
        if [[ "$attempts" -ge 30 ]]; then
            error "PocketBase did not become healthy after 30 attempts."
            error "Check logs: docker compose -f $INSTALL_DIR/docker-compose.yaml logs pocketbase"
            exit 1
        fi
        sleep 2
    done
    log "PocketBase is healthy."
}

# ── Summary ──────────────────────────────────────────────────────────────────

print_summary() {
    echo ""
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${GREEN}  AutoStack $AUTOSTACK_VERSION installed successfully${NC}"
    echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo "  Platform UI:   http://localhost:8090/_/"
    echo "  API:           http://localhost:8090/api/v1/"
    echo "  Grafana:       http://localhost:3000  (admin / autostack)"
    echo "  Prometheus:    http://localhost:9090"
    echo ""
    echo "  Config:        $INSTALL_DIR/.env"
    echo "  Data:          $DATA_DIR"
    echo ""
    echo "  Next steps:"
    echo "    1. Open http://localhost:8090/_/ and create your admin account"
    echo "    2. See docs/quickstart.md for your first deployment"
    echo "    3. See docs/security-boundaries.md before exposing to the internet"
    echo ""
    echo "  Stop:   docker compose -f $INSTALL_DIR/docker-compose.yaml down"
    echo "  Logs:   docker compose -f $INSTALL_DIR/docker-compose.yaml logs -f"
    echo ""
}

# ── Main ─────────────────────────────────────────────────────────────────────

main() {
    log "AutoStack Installer $AUTOSTACK_VERSION"
    check_docker
    check_compose
    check_memory
    setup_directories
    generate_secrets
    write_compose
    start_services
    print_summary
}

main "$@"
